# Generated by Django 4.2.2 on 2023-06-23 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_marketing_price_product_price_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variation',
            options={'verbose_name': 'Variation', 'verbose_name_plural': 'Variations'},
        ),
    ]
