# Generated by Django 4.2.2 on 2023-06-23 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'OrderItem', 'verbose_name_plural': 'OrderItems'},
        ),
    ]
