# Generated by Django 4.2.2 on 2023-07-03 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_orderitem_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quantity_total',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
