# Generated by Django 4.2.2 on 2023-07-03 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_order_quantity_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='variation_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
